commerce_payment.commerce_payment_gateway.plugin.ingenico_gc_offsite_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    api_key:
      type: string
      label: 'API key'
    api_secret:
      type: string
      label: 'API secret'
    integrator:
      type: string
      label: 'Integrator'
    merchant_id:
      type: string
      type: 'Merchant ID'
    subdomain:
      type: string
      type: 'Subdomain'