commerce_payment.commerce_payment_gateway.plugin.ingenico_gc_onsite:
  type: commerce_payment_gateway_configuration
  mapping:
    api_key:
      type: string
      label: 'API key'
    api_secret:
      type: string
      label: 'API secret'
    api_endpoint:
      type: string
      label: 'API endpoint'
    integrator:
      type: string
      label: 'Integrator'

commerce_payment.commerce_payment_gateway.plugin.ingenico_gc_offsite_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    api_key:
      type: string
      label: 'API key'
    api_secret:
      type: string
      label: 'API secret'
    api_endpoint:
      type: string
      label: 'API endpoint'
    integrator:
      type: string
      label: 'Integrator'
    redirect_method:
      type: string
      label: 'Redirect method'
